### ISSUE TITLE
Question: How to install it?

### ISSUE THREAD

**Issue by sys-auditing** [satcom886/NetBoard#12]
Hi,
i would like to install this tool, but i don't understand how to do.

Thank you.

**Comment by k8ieone** [comment]
Hi,
Thanks for your interest in my project.

If you just want to try it out, download the project, `cd` into it and run `python3 -m http.server 8080`. Most Linux distros ship with Python 3 so it should work pretty much anywhere. After you do that, you can just navigate to [localhost:8080](http://localhost:8080) and you should see the website load (it will be just a grey background at first). I can point you to how to configure your Netdata servers when you get there.

If you want a more permanent and/or public installation, I'm afraid that's a bit too much to explain step-by-step here.

**Comment by sys-auditing** [comment]
Hi,
thank you for your response.

I see, i want a more permanent installation, and my master server runs nginx web server, so does `python3 -m http.server 8080` will wokrs?

Thanks.

**Comment by k8ieone** [comment]
If you already have Nginx running, it should just be enough to drop the NetBoard folder into your document root.
